// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	CreateAEntries(ctx context.Context, arg CreateAEntriesParams) (Entries, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Accounts, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfers, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntries(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Accounts, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Accounts, error)
	GetEntries(ctx context.Context, id int64) (Entries, error)
	GetTransfer(ctx context.Context, id int64) (Transfers, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Accounts, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entries, error)
	ListTransfer(ctx context.Context, arg ListTransferParams) ([]Transfers, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Accounts, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Accounts, error)
	UpdateEntries(ctx context.Context, arg UpdateEntriesParams) (Entries, error)
	UpdateTransfer(ctx context.Context, arg UpdateTransferParams) (Transfers, error)
}

var _ Querier = (*Queries)(nil)
